# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-08-09 17:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Farm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Field',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15)),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dataapp.Farm')),
            ],
        ),
        migrations.CreateModel(
            name='FieldCrop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15)),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dataapp.Field')),
            ],
        ),
        migrations.CreateModel(
            name='Irrigation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('curr_smd', models.DecimalField(decimal_places=3, max_digits=20, null=True)),
                ('lw_smd', models.DecimalField(decimal_places=3, max_digits=20, null=True)),
                ('water_use', models.DecimalField(decimal_places=3, max_digits=20, null=True)),
                ('drainage', models.DecimalField(decimal_places=3, max_digits=20, null=True)),
                ('allowable_smd', models.DecimalField(decimal_places=3, max_digits=20, null=True)),
                ('fieldcrop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dataapp.FieldCrop')),
            ],
        ),
    ]
